name: RegEx text replacement
on: [push, pull_request, discussion_comment, issue_comment, fork]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "(&#40;/.*([a-rt-zA-RT-Z0-9]))$2([^?].*/i)"
          replace: "$1{2}$3"
          regex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
