name: RegEx text replacement
on: [push, pull_request, discussion_comment, issue_comment, fork]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: (:has-text\(/([a-zA-Z0-9øØåÅñ_.;,|/{}* !?"'-]|\\){0,}([a-rt-zA-RæÆøØåÅT-Z0-9]))$3([a-zA-Z0-9æÆøØåÅñ_.;,|/{}* !"'-]|\\)
          replace: "$1{2}$4"
          include: "**/a.txt"
          regex: true
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
